### ISSUE TITLE
HER export issues

### ISSUE THREAD

**Issue by dmgbk** [findsorguk/findsorguk#622] opened 2015-02-05 09:18 UTC
I have just tried to complete my first export since the recent work undertaken to the PAS database. Unfortunately all of the data in the export has been muddled or is missing. For example, all of the Date From data is in the Object Subclass column. All of the data for subsequent columns is also in the incorrect column. I am also missing data from some columns, e.g. County, District and Parish. It is all too jumbled for me to tell exactly what else is missing.

**Comment by portableant** [comment] 2015-02-05 09:28
Can you send by email to info@finds.org.uk the search you performed. We can then see what the problem is more easily. Thanks for raising this.
D

**Comment by portableant** [comment] 2015-02-09 23:52
Will be fixed tomorrow afternoon.

**Closed** 2015-02-10 12:42 UTC
