### ISSUE TITLE
Britannia articles not found on server

### ISSUE THREAD

**Issue by mchesterkadwell** [findsorguk/findsorguk#651] opened 2015-02-09 15:59 UTC
At the URL http://finds.org.uk/publications/research the Britannia article links do not work.

For example:
Not Found
The requested URL /publications/documents/britannia/2010.pdf was not found on this server.

**Comment by portableant** [comment] 2015-02-09 15:59
Duplicate of #629

**Closed by portableant** 2015-02-09 15:59 UTC

**Comment by mchesterkadwell** [comment] 2015-02-09 16:12
Oops, only searched for open issues.
