### ISSUE TITLE
Image upload problem for hoard (IARCH) records

### ISSUE THREAD

**Issue by irichardson77** [findsorguk/findsorguk#911] opened 2015-06-15 16:10 UTC
This has been encountered by both Eleanor Ghey and myself (Ian Richardson). Attempting to upload images to IARCH records results in the image being attached to a totally unrelated pre-existing database record. 

My particular experience was that I tried to upload an image to IARCH-EF70E8 and it instead attached to KENT1513. I deleted the image and tried again, with the same result.

**Comment by portableant** [comment] 2015-06-16 14:08
I'm really sorry, I won't have time to fix this before I go on leave. It is a reasonably sized job to track down all the errors that might cause this.

**Comment by s-moon** [comment] 2015-12-23 14:38
I think the problem is caused when it tries to attach the image to the record, but does so using code which handles images for normal objects. So, for example, when the hoard ID is 100, it tries to attach the image to record 100 but instead of using the hoards table, it attaches it to the finds one. In short, all image adding code adds to finds records (or mistakenly does). Hope that's clear?!?!

I need to dig into the code but I think it will need some kind of conditional logic to work out whether it is to affect a hoard record or a normal find one.

**Comment by portableant** [comment] 2017-11-20 23:08
This will be closed in caf10709b053193ab8b8e902176f6c7995d7063b 
It was quite a bit of logic to amend in the end.

**Closed** 2017-11-21 14:52 UTC
Labels: enhancement
